name: math_coding_foundry_agent_pr_workflow

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      use_case_base_path:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "math_coding_agent"
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      use_case_base_path:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "math_coding_agent"
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'math_coding_agent/**'
      - '.github/**'
      - 'llmops/**'
      - 'lib/**'

#=====================================
# Execute platform_pr_dev_workflow workflow for experiment, evaluation and deployment of flows
#=====================================
jobs:
  execute-platform-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yaml
    with:
      env_name: ${{ inputs.env_name || 'pr'}}
      use_case_base_path: ${{ inputs.flow_type || 'math_coding_agent' }}
    secrets: inherit